# Generated by Django 2.1.1 on 2018-09-13 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='time',
        ),
        migrations.AddField(
            model_name='submissions',
            name='subtime',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 20, 49, 16, 168758)),
        ),
    ]
