# Generated by Django 2.1.1 on 2018-09-11 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20180911_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='questiontitle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submissions',
            name='testCaseScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 17, 38, 15, 219300)),
        ),
    ]
