# Generated by Django 2.1.1 on 2018-09-11 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20180911_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 0, 27, 11, 102348)),
        ),
    ]
