# Generated by Django 2.1.1 on 2018-09-13 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20180913_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questiontitle',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 14, 57, 40, 765604)),
        ),
    ]
